<a href="https://colab.research.google.com/github/Fernandarodg/CinD_23-II/blob/main/05_Dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1.Libraries**

In [5]:
import numpy as np
import pandas as pd
import plotly.express as px

# **2. Import File**

* Upload the file to Colab
* Right click on the file and copy the path

In [7]:
# read the file

## Save the path
p = '/content/BASE DE EMPLEO Oficial.xlsx'

# Read ans create the dataframe
d = pd.read_excel(p)
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1120 entries, 0 to 1119
Data columns (total 13 columns):
 #   Column                                                                                 Non-Null Count  Dtype
---  ------                                                                                 --------------  -----
 0   Year                                                                                   1120 non-null   int64
 1   Country                                                                                1120 non-null   object
 2   GDP per capita (current US$)                                                           1120 non-null   object
 3   Total population                                                                       1120 non-null   int64
 4   Percentage of wage workers, total (modeled ILO estimate)                               1120 non-null   float64
 5   Own-account workers, total (% of total employment) (modeled ILO estimate))             1120 non-null   float64
 6   Vulnerable employment, total (% of total employment) (modeled ILO estimate)            1120 non-null   float64
 7   Unemployment, total (% of total labor force) (modeled ILO estimate)                    1120 non-null   float64
 8   DUnemployment, total youth (% of total labor force ages 15-24) (modeled ILO estimate)  1120 non-null   float64
 9   Labor force, total                                                                     1120 non-null   int64
 10  Employment in agriculture (% of total employment) (modeled ILO estimate)               1120 non-null   float64
 11  Employment in industry (% of total employment) (modeled ILO estimate)                  1120 non-null   float64
 12  Employment in services (% of total employment) (modeled ILO estimate)                  1120 non-null   float64
dtypes: float64(8), int64(3), object(2)
memory usage: 113.9+ KB

In [8]:
# Explore
d.head()

,Year,Country,GDP per capita (current US$),Total population,"Percentage of wage workers, total (modeled ILO estimate)","Own-account workers, total (% of total employment) (modeled ILO estimate))","Vulnerable employment, total (% of total employment) (modeled ILO estimate)","Unemployment, total (% of total labor force) (modeled ILO estimate)","DUnemployment, total youth (% of total labor force ages 15-24) (modeled ILO estimate)","Labor force, total",Employment in agriculture (% of total employment) (modeled ILO estimate),Employment in industry (% of total employment) (modeled ILO estimate),Employment in services (% of total employment) (modeled ILO estimate)
0,2014,Afghanistan,628.146804,32716210,13.98273,86.01729,84.494340,7.910,10.086,8285362,44.79854,22.046710,33.15474
1,2014,Angola,5059.080441,27128337,36.66563,63.33441,58.544130,9.580,16.428,11377486,57.59966,8.090238,34.31015
2,2014,Argentina,12334.798245,42669500,76.34650,23.65348,20.177971,7.270,19.132,19049721,8.59409,22.202530,69.20337
3,2014,Armenia,4017.229913,2889930,55.86226,44.13774,42.723298,11.862,20.650,1433898,34.82585,16.728490,48.44566
4,2014,Azerbaijan,7890.83525,9535079,33.25963,66.74039,56.673540,4.910,13.287,4531372,36.75345,14.304240,48.94229

In [9]:
# Explore
d.tail()

,Year,Country,GDP per capita (current US$),Total population,"Percentage of wage workers, total (modeled ILO estimate)","Own-account workers, total (% of total employment) (modeled ILO estimate))","Vulnerable employment, total (% of total employment) (modeled ILO estimate)","Unemployment, total (% of total labor force) (modeled ILO estimate)","DUnemployment, total youth (% of total labor force ages 15-24) (modeled ILO estimate)","Labor force, total",Employment in agriculture (% of total employment) (modeled ILO estimate),Employment in industry (% of total employment) (modeled ILO estimate),Employment in services (% of total employment) (modeled ILO estimate)
1115,2020,Low & middle income,4729.766987,6550746999,45.127069,54.872926,51.689324,6.983444,18.767489,2766670108,32.393221,22.629869,44.976909
1116,2020,North America,61461.121126,369582571,92.692745,7.307263,4.852925,8.205090,15.372998,186112720,1.725776,19.401736,78.872488
1117,2020,OECD members,38341.320759,1370222158,83.942631,16.057371,12.565100,7.102036,15.736501,667977804,4.823204,22.467883,72.708913
1118,2020,Pacific island small states,3713.506943,2566819,49.687011,50.313095,49.214219,3.285646,9.997612,951280,35.246459,12.660912,52.092524
1119,2020,Sub-Saharan Africa,1488.7955,1151302081,23.220315,76.779686,74.492834,6.627845,12.654512,437699034,51.959544,11.500442,36.540009

# **3.Cleaning**

## Column names

In [11]:
# Year to year
d.rename(columns = {'Year':'year'}, inplace = True)

# Total population to pop
d.rename(columns = {'Total population':'pop'}, inplace = True)

# GPD per capita to GDP
d.rename(columns = {'GDP per capita (current US$)':'GDP'}, inplace = True)

# Percentage of wage workers, total (modeled ILO estimate) to wage workers
d.rename(columns = {'Percentage of wage workers, total (modeled ILO estimate)':'wage workers'}, inplace = True)

# Own-account workers, total (% of total employment) (modeled ILO estimate)) to Own-account workers
d.rename(columns = {'Own-account workers, total (% of total employment) (modeled ILO estimate))':'Own-account workers'}, inplace = True)

# Vulnerable employment, total (% of total employment) (modeled ILO estimate) to  Vulnerable employment
d.rename(columns = {'Vulnerable employment, total (% of total employment) (modeled ILO estimate)':'Vulnerable employment'}, inplace = True)

d.head()

,year,Country,GDP,pop,wage workers,Own-account workers,Vulnerable employment,"Unemployment, total (% of total labor force) (modeled ILO estimate)","DUnemployment, total youth (% of total labor force ages 15-24) (modeled ILO estimate)","Labor force, total",Employment in agriculture (% of total employment) (modeled ILO estimate),Employment in industry (% of total employment) (modeled ILO estimate),Employment in services (% of total employment) (modeled ILO estimate)
0,2014,Afghanistan,628.146804,32716210,13.98273,86.01729,84.494340,7.910,10.086,8285362,44.79854,22.046710,33.15474
1,2014,Angola,5059.080441,27128337,36.66563,63.33441,58.544130,9.580,16.428,11377486,57.59966,8.090238,34.31015
2,2014,Argentina,12334.798245,42669500,76.34650,23.65348,20.177971,7.270,19.132,19049721,8.59409,22.202530,69.20337
3,2014,Armenia,4017.229913,2889930,55.86226,44.13774,42.723298,11.862,20.650,1433898,34.82585,16.728490,48.44566
4,2014,Azerbaijan,7890.83525,9535079,33.25963,66.74039,56.673540,4.910,13.287,4531372,36.75345,14.304240,48.94229

# Delete Columns

In [13]:
# d = d.drop(columns = ['Laborforce,total'])
# d.info()

# **4. Indexing**

In [14]:
# Duplicate the dataframe
d2 = d

In [15]:
# Duplicate year as string / how to create a column
d2['year_str'] = d2['year'].astype(str)
d2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1120 entries, 0 to 1119
Data columns (total 14 columns):
 #   Column                                                                                 Non-Null Count  Dtype
---  ------                                                                                 --------------  -----
 0   year                                                                                   1120 non-null   int64
 1   Country                                                                                1120 non-null   object
 2   GDP                                                                                    1120 non-null   object
 3   pop                                                                                    1120 non-null   int64
 4   wage workers                                                                           1120 non-null   float64
 5   Own-account workers                                                                    1120 non-null   float64
 6   Vulnerable employment                                                                  1120 non-null   float64
 7   Unemployment, total (% of total labor force) (modeled ILO estimate)                    1120 non-null   float64
 8   DUnemployment, total youth (% of total labor force ages 15-24) (modeled ILO estimate)  1120 non-null   float64
 9   Labor force, total                                                                     1120 non-null   int64
 10  Employment in agriculture (% of total employment) (modeled ILO estimate)               1120 non-null   float64
 11  Employment in industry (% of total employment) (modeled ILO estimate)                  1120 non-null   float64
 12  Employment in services (% of total employment) (modeled ILO estimate)                  1120 non-null   float64
 13  year_str                                                                               1120 non-null   object
dtypes: float64(8), int64(3), object(3)
memory usage: 122.6+ KB

In [20]:
# Indexing
idx = pd.MultiIndex.from_product([d2['Country'].unique(),range(d2.year.min(),d2.year.max()+1)],
                                 names = ['Country', 'year'])

## Attach the index
d2 = d2.set_index(['Country', 'year'])

d2.head()

,,GDP,pop,wage workers,Own-account workers,Vulnerable employment,"Unemployment, total (% of total labor force) (modeled ILO estimate)","DUnemployment, total youth (% of total labor force ages 15-24) (modeled ILO estimate)","Labor force, total",Employment in agriculture (% of total employment) (modeled ILO estimate),Employment in industry (% of total employment) (modeled ILO estimate),Employment in services (% of total employment) (modeled ILO estimate),year_str
Country,year,,,,,,,,,,,,
Afghanistan,2014,628.146804,32716210,13.98273,86.01729,84.494340,7.910,10.086,8285362,44.79854,22.046710,33.15474,2014
Angola,2014,5059.080441,27128337,36.66563,63.33441,58.544130,9.580,16.428,11377486,57.59966,8.090238,34.31015,2014
Argentina,2014,12334.798245,42669500,76.34650,23.65348,20.177971,7.270,19.132,19049721,8.59409,22.202530,69.20337,2014
Armenia,2014,4017.229913,2889930,55.86226,44.13774,42.723298,11.862,20.650,1433898,34.82585,16.728490,48.44566,2014
Azerbaijan,2014,7890.83525,9535079,33.25963,66.74039,56.673540,4.910,13.287,4531372,36.75345,14.304240,48.94229,2014

In [16]:
d2['Country'].unique()

array(['Afghanistan', 'Angola', 'Argentina', 'Armenia', 'Azerbaijan',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bhutan', 'Bolivia', 'Brunei Darussalam', 'Bulgaria',
       'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon',
       'Canada', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros',
       'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica', "Cote d'Ivoire",
       'Croatia', 'Cuba', 'Cyprus', 'Czechia', 'Denmark', 'Djibouti',
       'Dominican Republic', 'Ecuador', 'Egypt, Arab Rep.', 'El Salvador',
       'Equatorial Guinea', 'Estonia', 'Eswatini', 'Ethiopia', 'Fiji',
       'Finland', 'France', 'Gambia, The', 'Georgia', 'Germany', 'Ghana',
       'Greece', 'Hong Kong SAR, China', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran, Islamic Rep.', 'Iraq', 'Ireland', 'Israel',
       'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya',
       'Korea, Rep.', 'Kuwait', 'Kyrgyz Republic', 'Latvia', 'Lebanon',
       'Lesotho', 'Liberia', 'Libya', 'Lithuania', 'Luxembourg',
       'Macao SAR, China', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives',
       'Mali', 'Malta', 'Mauritania', 'Mauritius', 'Mexico', 'Moldova',
       'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar',
       'Namibia', 'Nicaragua', 'Niger', 'Nigeria', 'North Macedonia',
       'Norway', 'Oman', 'Pakistan', 'Panama', 'Papua New Guinea',
       'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal',
       'Puerto Rico', 'Qatar', 'Romania', 'Russian Federation', 'Samoa',
       'Saudi Arabia', 'Senegal', 'Serbia', 'Sierra Leone', 'Singapore',
       'Slovak Republic', 'Slovenia', 'Spain', 'Sri Lanka', 'St. Lucia',
       'St. Vincent and the Grenadines', 'Sudan', 'Suriname', 'Sweden',
       'Switzerland', 'Syrian Arab Republic', 'Tajikistan', 'Tanzania',
       'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago',
       'Tunisia', 'Turkiye', 'Turkmenistan', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela, RB', 'Vietnam',
       'Virgin Islands (U.S.)', 'West Bank and Gaza', 'Yemen, Rep.',
       'Zambia', 'Zimbabwe', 'Arab World', 'Low & middle income',
       'North America', 'OECD members', 'Pacific island small states',
       'Sub-Saharan Africa'], dtype=object)

In [17]:
range(d2.year.min(),d2.year.max()+1)

range(2014, 2021)